# k8s/overlays/local/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base
resources:
  - ../../base

# Patch the frontend service type to NodePort using a separate file
patches:
  - path: frontend-service-nodeport.yaml
    target:
      kind: Service
      name: frontend-service
      namespace: movie-explorer 