# k8s/base/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: movie-explorer-secrets
# Data will be populated by CI/CD or overlays
# Use stringData for easier local development overrides if needed
stringData:
  omdb-api-key: "YOUR_API_KEY_HERE" # Placeholder - MUST be overridden 